"""Diagnostics support for AC Infinity AIRTAP.

Everything here is read-only snapshots; no BLE traffic is generated by
downloading diagnostics (a GATT connection for a diagnostics dump would
steal a proxy slot from real work for zero benefit).
"""
from __future__ import annotations

import dataclasses
import time
from typing import Any

from homeassistant.components import bluetooth
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_ADDRESS, CONF_SERVICE_DATA
from homeassistant.core import HomeAssistant

from .const import DOMAIN
from .models import ACInfinityData


def _redact_address(address: str | None) -> str | None:
    """Redact a BLE MAC down to its last four hex digits.

    Enough to correlate a diagnostics dump with a specific fan out of the
    fleet without publishing the full address in bug reports.
    """
    if not address:
        return address
    return f"**:**:**:**:{address[-5:]}"


def _as_plain_dict(value: Any) -> Any:
    """Return dataclasses as dicts so the dump is JSON-serializable."""
    if dataclasses.is_dataclass(value) and not isinstance(value, type):
        return dataclasses.asdict(value)
    return value


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant, entry: ConfigEntry
) -> dict[str, Any]:
    """Return diagnostics for a config entry."""
    data: ACInfinityData = hass.data[DOMAIN][entry.entry_id]
    device = data.device
    coordinator = data.coordinator
    address: str = entry.data[CONF_ADDRESS]

    service_info = bluetooth.async_last_service_info(
        hass, address.upper(), connectable=True
    )
    advertisement: dict[str, Any] = {
        "age_seconds": None,
        "rssi": None,
        "source": None,
        "tx_power": None,
    }
    if service_info is not None:
        advertisement = {
            # service_info.time is monotonic-clock based (coarse variant);
            # the delta to time.monotonic() is milliseconds — irrelevant at
            # the seconds granularity that matters here.
            "age_seconds": round(time.monotonic() - service_info.time, 1),
            "rssi": service_info.rssi,
            # Which ESPHome proxy (or local adapter) last saw the device —
            # the first thing to check when one fan of the fleet goes stale.
            "source": service_info.source,
            "tx_power": service_info.tx_power,
        }

    return {
        "entry": {
            "title": entry.title,
            "address": _redact_address(address),
            "service_data": _as_plain_dict(entry.data.get(CONF_SERVICE_DATA)),
        },
        "device": {
            "name": device.name,
            "state": _as_plain_dict(device.state),
            "rssi_at_last_parse": device.rssi,
            # Provided by the vendored controller's freshness tracking;
            # getattr keeps diagnostics working even if the vendored lib is
            # swapped for an upstream build without it.
            "advertisement_age_seconds": getattr(device, "advertisement_age", None),
            "connection_stats": _as_plain_dict(
                getattr(device, "connection_stats", None)
            ),
        },
        "coordinator": {
            "available": coordinator.available,
            "last_poll_successful": coordinator.last_poll_successful,
        },
        "bluetooth": {
            "connectable_path_available": bool(
                bluetooth.async_ble_device_from_address(
                    hass, address.upper(), connectable=True
                )
            ),
            "connectable_scanner_count": bluetooth.async_scanner_count(
                hass, connectable=True
            ),
        },
    }
